In [1]:
import math

In [2]:
math.pi

3.141592653589793

In [3]:
math.sqrt(4)

2.0

In [4]:
math.ceil(2.1) #rounds a decimal number up to the nearest integer

3

In [5]:
math.floor(2.9) # rounds a decimal number down to the nearest integer

2

In [6]:
from math import pi

In [7]:
pi

3.141592653589793

In [8]:
list1=[8,9,7,5,4]
list2=[5,7,3,6,1]

In [9]:
sum_list=[]
for num1,num2 in zip(list1,list2):
    sum_list.append(num1+num2)
sum_list
    

[13, 16, 10, 11, 5]

In [10]:
import numpy as np
arr1=np.array(list1)
arr2=np.array(list2)

In [11]:
sum_arr=arr1+arr2
sum_arr

array([13, 16, 10, 11,  5])

In [12]:
height=[1.73,1.68,1.23,1.44]
weight=[65.4,71.3,53.2,56.2]
#bmi=weight/height**2
bmi_list=[]
for i,j in zip(weight,height):
  bmi_list.append(i/j**2)
bmi_list

[21.85171572722109, 25.262188208616784, 35.16425408156521, 27.102623456790127]

In [13]:
arr_h=np.array(height)
arr_w=np.array(weight)
bmi_arr=arr_w/arr_h**2
bmi_arr


array([21.85171573, 25.26218821, 35.16425408, 27.10262346])

In [20]:
list1=[1,"Hi",True,6,"WelcometoBrototype",7]

In [21]:
arr1=np.array(list1)

In [22]:
arr1


array(['1', 'Hi', 'True', '6', 'WelcometoBrototype', '7'], dtype='<U18')

In [23]:
arr1=np.array([1,2,3,4,5])

In [24]:
arr1.ndim#dimension of the array

1

In [25]:
arr1.dtype #datatype of the array

dtype('int32')

In [26]:
type(arr1)

numpy.ndarray

In [28]:
arr2=np.array([[1,2,3],[4,5,6]])

In [31]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
arr2.dtype

dtype('int32')

In [30]:
type(arr2)

numpy.ndarray

In [32]:
arr2.ndim

2

In [33]:
arr2.shape

(2, 3)

In [35]:
print(list(range(1,11)))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [36]:
arr3=np.arange(4,20)
arr3

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [37]:
arr3.reshape(4,4)

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [38]:
arr3.reshape(2,8)

array([[ 4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19]])

In [39]:
arr3.reshape(8,2)

array([[ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [40]:
#Array Slicing
arr4=np.arange(16)
arr4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [42]:
arr4[5]

5

In [46]:
arr4[5:11]

array([ 5,  6,  7,  8,  9, 10])

In [47]:
arr4[:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
arr4[10:]

array([10, 11, 12, 13, 14, 15])

In [49]:
#2,9,12
arr4[[2,9,12]]

array([ 2,  9, 12])

In [50]:
arr5=np.array([[7,8,9,12],[5,6,8,9],[7,8,9,1]])

In [51]:
arr5.ndim

2

In [52]:
arr5.shape

(3, 4)

In [53]:
arr5[2] #print the 2nd row 

array([7, 8, 9, 1])

In [54]:
arr5

array([[ 7,  8,  9, 12],
       [ 5,  6,  8,  9],
       [ 7,  8,  9,  1]])

In [55]:
arr5[2,1]

8

In [56]:
arr5[:,2] #All rows of column2

array([9, 8, 9])

In [57]:
arr5[:,1]# all rows of 1st column

array([8, 6, 8])

In [58]:
arr5[1,:] # All columns of 1st row

array([5, 6, 8, 9])

In [59]:
arr6=np.arange(10,82,2)

In [60]:
arr6

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76,
       78, 80])

In [64]:
arr6=np.arange(10,82,2).reshape(6,6)

In [65]:
arr6

array([[10, 12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30, 32],
       [34, 36, 38, 40, 42, 44],
       [46, 48, 50, 52, 54, 56],
       [58, 60, 62, 64, 66, 68],
       [70, 72, 74, 76, 78, 80]])

In [67]:
arr6[3]

array([46, 48, 50, 52, 54, 56])

In [68]:
arr6[:3]
#from 0th row to 2nd row

array([[10, 12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30, 32],
       [34, 36, 38, 40, 42, 44]])

In [69]:
arr6[:,3]

array([16, 28, 40, 52, 64, 76])

In [71]:
arr6[:,[0,3]]# all rows of 0th column and 3rd column

array([[10, 16],
       [22, 28],
       [34, 40],
       [46, 52],
       [58, 64],
       [70, 76]])

In [73]:
arr6[:,0:3] #All rows of 0th column to 2nd column

array([[10, 12, 14],
       [22, 24, 26],
       [34, 36, 38],
       [46, 48, 50],
       [58, 60, 62],
       [70, 72, 74]])

In [74]:
arr6[1:3,1:3] #1st row and 2nd row of 1st and 2nd column

array([[24, 26],
       [36, 38]])

In [75]:
arr5

array([[ 7,  8,  9, 12],
       [ 5,  6,  8,  9],
       [ 7,  8,  9,  1]])

In [76]:
arr5.sum()

89

In [77]:
np.sum(arr5)

89

In [78]:
arr5.mean()

7.416666666666667

In [79]:
np.mean(arr5)

7.416666666666667

In [82]:
np.median(arr5)

8.0

In [83]:
arr5.mean(axis=1) #row wise mean

array([9.  , 7.  , 6.25])

In [84]:
arr5.mean(axis=0) #column wise mean

array([6.33333333, 7.33333333, 8.66666667, 7.33333333])

In [85]:
arr5.sum(axis=1)#row wise sum

array([36, 28, 25])

In [86]:
np.sum(arr5,axis=1)

array([36, 28, 25])

In [87]:
np.sum(arr5,axis=0)

array([19, 22, 26, 22])

In [88]:
arr5.sum(0) #columnwise sum

array([19, 22, 26, 22])

In [89]:
arr5.sum(1) #ROWWISE SUM

array([36, 28, 25])

In [90]:
arr5+5 #scalar operations

array([[12, 13, 14, 17],
       [10, 11, 13, 14],
       [12, 13, 14,  6]])

In [91]:
arr5*5

array([[35, 40, 45, 60],
       [25, 30, 40, 45],
       [35, 40, 45,  5]])

In [92]:
arr5[2]=-9

In [93]:
arr5

array([[ 7,  8,  9, 12],
       [ 5,  6,  8,  9],
       [-9, -9, -9, -9]])

In [94]:
np.abs(arr5)

array([[ 7,  8,  9, 12],
       [ 5,  6,  8,  9],
       [ 9,  9,  9,  9]])

In [95]:
np.sqrt(arr5)


C:\Users\vrlin\AppData\Local\Temp\ipykernel_9768\2987985467.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr5)


array([[2.64575131, 2.82842712, 3.        , 3.46410162],
       [2.23606798, 2.44948974, 2.82842712, 3.        ],
       [       nan,        nan,        nan,        nan]])

In [97]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [104]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [103]:
np.eye(4)#identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [101]:
arr6


array([[10, 12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30, 32],
       [34, 36, 38, 40, 42, 44],
       [46, 48, 50, 52, 54, 56],
       [58, 60, 62, 64, 66, 68],
       [70, 72, 74, 76, 78, 80]])

In [102]:
arr6.T

array([[10, 22, 34, 46, 58, 70],
       [12, 24, 36, 48, 60, 72],
       [14, 26, 38, 50, 62, 74],
       [16, 28, 40, 52, 64, 76],
       [18, 30, 42, 54, 66, 78],
       [20, 32, 44, 56, 68, 80]])

In [2]:
import numpy as np

In [4]:
data=np.array([21,3,13,14,15])


In [5]:
Q1=np.percentile(data,25)
Q3=np.percentile(data,75)

In [6]:
Q3-Q1

2.0