In [1]:
import numpy as np


In [7]:
from time import process_time

In [25]:
python_list=[i for i in range(10000)]
start_time=process_time()
python_list=[i+5 for i in python_list]
end_time=process_time()
print(end_time-start_time)

0.0


In [35]:
np_array=np.array([i for i in range(10000)])
start_time=process_time()
np_array += 5
end_time=process_time()
print(end_time-start_time)

0.0


In [41]:
list1=[1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [45]:
np_array=np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [51]:
#Creating a 1D array
a=np.array([1,2,3,4])
print(a)


[1 2 3 4]


In [55]:
a.shape #4 represents no of columns

(4,)

In [63]:
#2D array
b=np.array([[1,2,3,4],[5,6,7,8]]) #similar to 2x4 matrix
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [65]:
b.shape

(2, 4)

In [67]:
#2D array with float
c=np.array([(1,2,3,4),(5,6,7,8)],dtype=float)

In [69]:
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


In [73]:
#Initial placeholders in numpy arrays
#create numpy array of zeros
x=np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [79]:
#create numpy array of ones
y=np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [83]:
# create an array of particular value
z=np.full((5,4),5)# 5x4 mattrix with all values 5
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [89]:
#create an identity matrix
c=np.eye(4)#specify shape 4x4
print(c)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [99]:
#create numpy array with random values
d=np.random.random((3,4))
print(d)# here we get value between 0 and 1

[[0.62658693 0.88451231 0.00907587 0.67799843]
 [0.88858188 0.97721773 0.7393612  0.19157971]
 [0.8504422  0.57280153 0.18959825 0.30423733]]


In [107]:
#array with random int valueswithin a specific range
e= np.random.randint(10,100,(3,5))
print(e)


[[40 20 11 14 42]
 [52 54 14 90 95]
 [97 35 89 85 98]]


In [115]:
#array of evenly spaced values, #Specifying the number of values required
f=np.linspace(10,30,5)
print(f) # here we get 5 values

[10. 15. 20. 25. 30.]


In [119]:
f=np.linspace(10,30,6)
f

array([10., 14., 18., 22., 26., 30.])

In [127]:
f=np.linspace(10,30,3)
f

array([10., 20., 30.])

In [129]:
g=np.arange(10,30)
g

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

In [135]:
g=np.arange(10,30,2)#2 step size similar to range() of list
g

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [143]:
#convert a list to a numpy array
list1=[1,2,3,4]
np_array=np.asarray(list1)#to covert one datatype to numpy array
print(np_array)
print(type(np_array))

[1 2 3 4]
<class 'numpy.ndarray'>


In [145]:
#Analysing numpy array


In [149]:
c=np.random.randint(10,90,(5,5))
print(c)

[[56 59 88 38 17]
 [68 81 64 41 83]
 [50 17 50 68 23]
 [75 62 82 30 74]
 [29 16 81 25 76]]


In [153]:
c.shape#array dimension

(5, 5)

In [155]:
#Number of dimension
c.ndim

2

In [157]:
#number of elements in an array
c.size

25

In [159]:
#The datatype of values in the array
c.dtype

dtype('int32')

In [161]:
#Mathematical operations on numpy array

In [163]:
list1=[1,2,3,4,5]
list2=[6,7,8,9,10]
print(list1+list2)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


Concatenated the lists

In [167]:
a=np.random.randint(0,10,(3,3))
b=np.random.randint(10,20,(3,3))


In [169]:
print(a)
print(b)

[[1 3 5]
 [8 6 0]
 [6 4 2]]
[[15 10 18]
 [11 19 17]
 [12 11 10]]


In [173]:
print(a+b)#elementwise  adddition

[[16 13 23]
 [19 25 17]
 [18 15 12]]


In [175]:
print(a-b)
print(a*b)
print(a/b)

[[-14  -7 -13]
 [ -3 -13 -17]
 [ -6  -7  -8]]
[[ 15  30  90]
 [ 88 114   0]
 [ 72  44  20]]
[[0.06666667 0.3        0.27777778]
 [0.72727273 0.31578947 0.        ]
 [0.5        0.36363636 0.2       ]]


In [177]:
print(np.add(a,b))

[[16 13 23]
 [19 25 17]
 [18 15 12]]


In [179]:
print(np.subtract(a,b))

[[-14  -7 -13]
 [ -3 -13 -17]
 [ -6  -7  -8]]


In [181]:
print(np.multiply(a,b))

[[ 15  30  90]
 [ 88 114   0]
 [ 72  44  20]]


In [183]:
print(np.divide(a,b))

[[0.06666667 0.3        0.27777778]
 [0.72727273 0.31578947 0.        ]
 [0.5        0.36363636 0.2       ]]


In [185]:
#Array Manupulation

In [187]:
array=np.random.randint(0,10,(2,3))

In [189]:
print(array)

[[5 1 1]
 [8 4 1]]


In [191]:
trans=np.transpose(array)
print(trans)
print(trans.shape)

[[5 8]
 [1 4]
 [1 1]]
(3, 2)


In [193]:
trans2=array.T
print(trans2)

[[5 8]
 [1 4]
 [1 1]]


In [195]:
#Reshaping the arrray
a=np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[6 3 6]
 [2 0 5]]
(2, 3)


In [197]:
b=a.reshape(3,2)

In [199]:
print(b)
print(b.shape)

[[6 3]
 [6 2]
 [0 5]]
(3, 2)
