In [1]:
import numpy as np

In [3]:
##create arrays using numpys
##Create 1D array
arr1=np.array([1,2,3,4,5])

In [5]:
print(type(arr1))
print(arr1.shape)# #say 1D array with 5 elemnts ,neversay 1row with 5 columns

<class 'numpy.ndarray'>
(5,)


In [16]:
arr2=np.array([1,2,3,4,5])
arr2=arr2.reshape(1,5)# reshaping this 1D array into 1 rows and two columns then it is converted into 2D array
print(arr2)

[[1 2 3 4 5]]


2 square bracket mens 2D array

In [18]:
print(arr2.ndim)

2


In [20]:
arr3=np.array([[1,2,3,4,5]])

In [24]:
print(arr3.shape)

(1, 5)


In [26]:
print(arr3.ndim)

2


In [28]:
arr4=np.array([[1,2,3,4,5],[2,3,4,5,6]])

In [30]:
print(arr4)

[[1 2 3 4 5]
 [2 3 4 5 6]]


In [32]:
print(arr4.ndim)

2


In [46]:
print(arr4.dtype)# may vary based on platform

int32


In [52]:
print(arr4.size)# total number of elemnts

10


In [57]:
print(arr4.itemsize) #based on platform in bytes

4


In [36]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [38]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [42]:
##Identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Numpy vectorized Operations

In [63]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])
print(arr1+arr2) #Addition

[11 22 33 44 55]


In [65]:
print(arr1-arr2)

[ -9 -18 -27 -36 -45]


In [71]:
arr=arr1*arr2
print(arr)

[ 10  40  90 160 250]


In [81]:
print(arr1/arr2)

[0.1 0.1 0.1 0.1 0.1]


## universal Function(ufunc)

In [99]:
arr=np.array([1,2,3,4,5]) # applying these functions to each elemnt in the array

In [91]:
print(np.sqrt(arr))

[1.         1.41421356 1.73205081 2.         2.23606798]


In [93]:
print(np.exp(arr))

[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [95]:
print(np.sin(arr))

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


In [97]:
print(np.log(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]


## Array Slicing and Indexing

In [105]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [107]:
arr[0] #will givw 0th row

array([1, 2, 3, 4])

In [113]:
arr[0][0] #0throw andd 0th column

1

In [119]:
arr[1:,2:]#will get 1st row to last row and 2nd column to last column

array([[ 7,  8],
       [11, 12]])

In [125]:
arr[:,1:3]# to remove 0th and last column

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [127]:
arr[1:4,]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [129]:
arr[:2,2:]

array([[3, 4],
       [7, 8]])

In [131]:
arr[1:,1:3]

array([[ 6,  7],
       [10, 11]])

# Modify array elements

In [134]:
arr[0][0]=100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [136]:
arr[1:]=100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


## Statistical concepts-Normalization
# to have a mean of 0 and SD of 1

In [143]:
data=np.array([1,2,3,4,5])
mean=np.mean(data)
std_dv=np.std(data)

#Normalize the data
normalized_data=(data-mean)/std_dv

print(normalized_data)

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


## Logical operation

In [148]:
data=np.array([1,2,3,4,5,6,7,8,9])


In [150]:
data>5

array([False, False, False, False, False,  True,  True,  True,  True])

In [152]:
data[data>5]

array([6, 7, 8, 9])

In [154]:
data[(data>=5) & (data<=8)]

array([5, 6, 7, 8])